In [2]:
import pandas as pd

In [5]:
df = pd.read_csv('state-areas.csv')

In [6]:
df

                   state  area (sq. mi)
0                Alabama          52423
1                 Alaska         656425
2                Arizona         114006
3               Arkansas          53182
4             California         163707
5               Colorado         104100
6            Connecticut           5544
7               Delaware           1954
8                Florida          65758
9                Georgia          59441
10                Hawaii          10932
11                 Idaho          83574
12              Illinois          57918
13               Indiana          36420
14                  Iowa          56276
15                Kansas          82282
16              Kentucky          40411
17             Louisiana          51843
18                 Maine          35387
19              Maryland          12407
20         Massachusetts          10555
21              Michigan          96810
22             Minnesota          86943
23           Mississippi          48434
24              Missouri          69709
25               Montana         147046
26              Nebraska          77358
27                Nevada         110567
28         New Hampshire           9351
29            New Jersey           8722
30            New Mexico         121593
31              New York          54475
32        North Carolina          53821
33          North Dakota          70704
34                  Ohio          44828
35              Oklahoma          69903
36                Oregon          98386
37          Pennsylvania          46058
38          Rhode Island           1545
39        South Carolina          32007
40          South Dakota          77121
41             Tennessee          42146
42                 Texas         268601
43                  Utah          84904
44               Vermont           9615
45              Virginia          42769
46            Washington          71303
47         West Virginia          24231
48             Wisconsin          65503
49               Wyoming          97818
50  District of Columbia             68
51           Puerto Rico           3515

In [23]:
df = pd.read_csv('state-population.csv')#导入数据
print(df.population.mean())
print(df.population.std())
df =df.tail()
df.to_csv('new.csv')#导出数据

6805558.401347068
28550144.966823243

In [14]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('weather_2012.sqlite')

tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)
print(tables)

df = pd.read_sql("SELECT * FROM weather_2012", conn)
df.head()

                                 name
0                     sqlite_sequence
1          ./data/weather_2012.sqlite
2   ./data/weather_2013_dancer.sqlite
3                       dacner_table1
4                       dancer_table1
5                        weather_2012
6                          1705_table
7                      1705_db.sqlite
8                          1706_score
9                          1706_table
10                        1706_table1
11                         1cer_table
12                             dancer
13                               bobo
14                               haha
15                         db_table_2
16                           sql_data
17                          sql_data1

,index,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,0.0,2012-01-01 00:00:00,-1.8,-3.9,86.0,4.0,8.0,101.24,Fog
1,1.0,2012-01-01 01:00:00,-1.8,-3.7,87.0,4.0,8.0,101.24,Fog
2,2.0,2012-01-01 02:00:00,-1.8,-3.4,89.0,7.0,4.0,101.26,"Freezing Drizzle,Fog"
3,3.0,2012-01-01 03:00:00,-1.5,-3.2,88.0,6.0,4.0,101.27,"Freezing Drizzle,Fog"
4,4.0,2012-01-01 04:00:00,-1.5,-3.3,88.0,7.0,4.8,101.23,Fog